---
- name: Deploy Nginx on target server
  hosts: webserver
  become: yes
  tasks:
    - name: Update apt repository
      apt:
        update_cache: yes

    - name: Install Nginx
      apt:
        name: nginx
        state: present

    - name: Ensure Nginx is running
      service:
        name: nginx
        state: started
        enabled: yes
